name: privateroom
description: A private room chat application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # firebase
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5

  # encryption
  encrypt: ^4.0.1

  # UI
  font_awesome_flutter: ^8.8.1
  rflutter_alert: ^1.0.3
  modal_progress_hud: ^0.1.3

  # UI utility
  flutter_speed_dial: ^1.2.5
  flutter_colorpicker: ^0.3.4


  # Date formatting
  intl: ^0.16.1

  # storage
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 100
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 900
